# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcommand.proto\x12\x06rocket"y\n\x07\x43ommand\x12\n\n\x02ud\x18\x01 \x01(\x05\x12\n\n\x02lr\x18\x02 \x01(\x05\x12\x10\n\x08throttle\x18\x03 \x01(\x05\x12\x10\n\x08override\x18\x04 \x01(\x08\x12\x0b\n\x03\x61rm\x18\x05 \x01(\x08\x12\x0e\n\x06\x64isarm\x18\x06 \x01(\x08\x12\x15\n\rthrottle_diff\x18\x07 \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "command_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_COMMAND"]._serialized_start = 25
    _globals["_COMMAND"]._serialized_end = 146
# @@protoc_insertion_point(module_scope)
