/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pacejka_model_zogpmc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {31, 1, 1};
static const casadi_int casadi_s3[3] = {12, 1, 1};

/* pacejka_model_zogpmc_expl_vde_adj:(i0[9],i1[9],i2[3],i3[31])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][3] : 0;
  a04=arg[1]? arg[1][1] : 0;
  a05=(a03*a04);
  a05=(a02*a05);
  a01=sin(a01);
  a06=arg[0]? arg[0][4] : 0;
  a07=(a06*a04);
  a07=(a01*a07);
  a05=(a05-a07);
  a07=arg[1]? arg[1][0] : 0;
  a08=(a06*a07);
  a08=(a02*a08);
  a05=(a05-a08);
  a08=(a03*a07);
  a08=(a01*a08);
  a05=(a05-a08);
  if (res[0]!=0) res[0][2]=a05;
  a05=arg[3]? arg[3][28] : 0;
  a08=(a03<a05);
  a09=(!a08);
  a10=arg[3]? arg[3][12] : 0;
  a11=arg[0]? arg[0][5] : 0;
  a12=(a10*a11);
  a12=(a12-a06);
  a13=casadi_sq(a12);
  a14=casadi_sq(a03);
  a15=(a13+a14);
  a16=(a12/a15);
  a17=arg[3]? arg[3][21] : 0;
  a18=arg[3]? arg[3][20] : 0;
  a19=5.0000000000000000e-01;
  a20=(a19*a12);
  a21=casadi_sq(a05);
  a22=(a21+a13);
  a20=(a20/a22);
  a23=3.;
  a24=2.;
  a24=(a24*a05);
  a23=(a23/a24);
  a25=(a12/a05);
  a26=atan(a25);
  a27=(a23*a26);
  a27=(a20+a27);
  a28=(a27*a03);
  a29=-1.;
  a24=(a24*a05);
  a30=(a24*a05);
  a29=(a29/a30);
  a26=(a29*a26);
  a30=(a12/a24);
  a13=(a13+a21);
  a30=(a30/a13);
  a26=(a26-a30);
  a31=(a26*a03);
  a32=(a31*a03);
  a33=(a32*a03);
  a28=(a28+a33);
  a28=(a08?a28:0);
  a33=atan2(a12,a03);
  a33=(a09?a33:0);
  a28=(a28+a33);
  a28=(a17*a28);
  a33=atan(a28);
  a33=(a18*a33);
  a33=cos(a33);
  a34=arg[3]? arg[3][19] : 0;
  a35=arg[1]? arg[1][4] : 0;
  a36=arg[3]? arg[3][14] : 0;
  a35=(a35/a36);
  a37=arg[1]? arg[1][5] : 0;
  a38=arg[3]? arg[3][15] : 0;
  a37=(a37/a38);
  a38=(a10*a37);
  a38=(a35-a38);
  a34=(a34*a38);
  a33=(a33*a34);
  a18=(a18*a33);
  a33=1.;
  a28=casadi_sq(a28);
  a28=(a33+a28);
  a18=(a18/a28);
  a17=(a17*a18);
  a16=(a16*a17);
  a16=(-a16);
  a16=(a09?a16:0);
  a18=(a11*a35);
  a18=(a36*a18);
  a16=(a16-a18);
  a32=(a32*a17);
  a32=(a08?a32:0);
  a16=(a16+a32);
  a32=(a03*a17);
  a31=(a31*a32);
  a31=(a08?a31:0);
  a16=(a16+a31);
  a31=(a03*a32);
  a26=(a26*a31);
  a26=(a08?a26:0);
  a16=(a16+a26);
  a27=(a27*a17);
  a27=(a08?a27:0);
  a16=(a16+a27);
  a27=arg[3]? arg[3][26] : 0;
  a26=(a27*a03);
  a18=casadi_sign(a03);
  a28=arg[1]? arg[1][3] : 0;
  a28=(a28/a36);
  a18=(a18*a28);
  a26=(a26*a18);
  a16=(a16-a26);
  a26=(a03*a18);
  a27=(a27*a26);
  a16=(a16-a27);
  a27=arg[3]? arg[3][25] : 0;
  a27=(a27*a18);
  a16=(a16-a27);
  a27=arg[3]? arg[3][13] : 0;
  a18=(a27*a11);
  a18=(a06+a18);
  a26=casadi_sq(a18);
  a14=(a26+a14);
  a34=(a18/a14);
  a38=arg[3]? arg[3][18] : 0;
  a39=arg[3]? arg[3][17] : 0;
  a40=(a18/a05);
  a41=(-a40);
  a41=atan(a41);
  a42=(a23*a41);
  a43=(a19*a18);
  a44=(a21+a26);
  a43=(a43/a44);
  a42=(a42-a43);
  a45=(a42*a03);
  a41=(a29*a41);
  a46=(a18/a24);
  a26=(a26+a21);
  a46=(a46/a26);
  a41=(a41+a46);
  a21=(a41*a03);
  a47=(a21*a03);
  a48=(a47*a03);
  a45=(a45+a48);
  a45=(a08?a45:0);
  a48=arg[0]? arg[0][7] : 0;
  a49=(-a18);
  a49=atan2(a49,a03);
  a49=(a48+a49);
  a49=(a09?a49:0);
  a45=(a45+a49);
  a45=(a38*a45);
  a49=atan(a45);
  a49=(a39*a49);
  a50=cos(a49);
  a51=arg[3]? arg[3][16] : 0;
  a52=cos(a48);
  a53=(a52*a37);
  a53=(a27*a53);
  a54=(a52*a35);
  a53=(a53+a54);
  a48=sin(a48);
  a54=(a48*a28);
  a53=(a53-a54);
  a53=(a51*a53);
  a50=(a50*a53);
  a39=(a39*a50);
  a45=casadi_sq(a45);
  a45=(a33+a45);
  a39=(a39/a45);
  a38=(a38*a39);
  a34=(a34*a38);
  a34=(a09?a34:0);
  a16=(a16+a34);
  a47=(a47*a38);
  a47=(a08?a47:0);
  a16=(a16+a47);
  a47=(a03*a38);
  a21=(a21*a47);
  a21=(a08?a21:0);
  a16=(a16+a21);
  a21=(a03*a47);
  a41=(a41*a21);
  a41=(a08?a41:0);
  a16=(a16+a41);
  a42=(a42*a38);
  a42=(a08?a42:0);
  a16=(a16+a42);
  a42=arg[3]? arg[3][23] : 0;
  a41=arg[0]? arg[0][6] : 0;
  a34=arg[3]? arg[3][27] : 0;
  a39=(a33-a34);
  a45=(a48*a37);
  a45=(a27*a45);
  a50=(a48*a35);
  a45=(a45+a50);
  a50=(a52*a28);
  a45=(a45+a50);
  a45=(a39*a45);
  a34=(a34*a28);
  a45=(a45+a34);
  a34=(a41*a45);
  a34=(a42*a34);
  a16=(a16-a34);
  a34=(a01*a04);
  a16=(a16+a34);
  a34=(a02*a07);
  a16=(a16+a34);
  if (res[0]!=0) res[0][3]=a16;
  a15=(a03/a15);
  a15=(a15*a17);
  a17=(-a15);
  a17=(a09?a17:0);
  a12=(a12+a12);
  a30=(a30/a13);
  a31=(a03*a31);
  a30=(a30*a31);
  a30=(a12*a30);
  a13=(a31/a13);
  a13=(a13/a24);
  a30=(a30-a13);
  a31=(a29*a31);
  a25=casadi_sq(a25);
  a25=(a33+a25);
  a31=(a31/a25);
  a31=(a31/a05);
  a30=(a30+a31);
  a31=(a23*a32);
  a31=(a31/a25);
  a31=(a31/a05);
  a30=(a30+a31);
  a20=(a20/a22);
  a20=(a20*a32);
  a12=(a12*a20);
  a30=(a30-a12);
  a32=(a32/a22);
  a32=(a19*a32);
  a30=(a30+a32);
  a32=(-a30);
  a32=(a08?a32:0);
  a17=(a17+a32);
  a11=(a11*a28);
  a11=(a36*a11);
  a17=(a17+a11);
  a14=(a03/a14);
  a14=(a14*a38);
  a11=(-a14);
  a11=(a09?a11:0);
  a17=(a17+a11);
  a21=(a03*a21);
  a11=(a21/a26);
  a11=(a11/a24);
  a18=(a18+a18);
  a46=(a46/a26);
  a46=(a46*a21);
  a46=(a18*a46);
  a11=(a11-a46);
  a29=(a29*a21);
  a40=casadi_sq(a40);
  a33=(a33+a40);
  a29=(a29/a33);
  a29=(a29/a05);
  a11=(a11-a29);
  a43=(a43/a44);
  a43=(a43*a47);
  a18=(a18*a43);
  a11=(a11+a18);
  a44=(a47/a44);
  a19=(a19*a44);
  a11=(a11-a19);
  a23=(a23*a47);
  a23=(a23/a33);
  a23=(a23/a05);
  a11=(a11-a23);
  a23=(a08?a11:0);
  a17=(a17+a23);
  a02=(a02*a04);
  a17=(a17+a02);
  a01=(a01*a07);
  a17=(a17-a01);
  if (res[0]!=0) res[0][4]=a17;
  a15=(a10*a15);
  a15=(a09?a15:0);
  a17=(a36*a03);
  a17=(a17*a35);
  a15=(a15-a17);
  a10=(a10*a30);
  a10=(a08?a10:0);
  a15=(a15+a10);
  a36=(a36*a06);
  a36=(a36*a28);
  a15=(a15+a36);
  a14=(a27*a14);
  a14=(-a14);
  a14=(a09?a14:0);
  a15=(a15+a14);
  a11=(a27*a11);
  a08=(a08?a11:0);
  a15=(a15+a08);
  a08=arg[1]? arg[1][2] : 0;
  a15=(a15+a08);
  if (res[0]!=0) res[0][5]=a15;
  a15=arg[3]? arg[3][22] : 0;
  a42=(a42*a03);
  a15=(a15-a42);
  a45=(a15*a45);
  if (res[0]!=0) res[0][6]=a45;
  a15=(a15*a41);
  a15=(a15*a39);
  a39=(a15*a27);
  a39=(a39*a37);
  a39=(a52*a39);
  a49=sin(a49);
  a51=(a51*a49);
  a27=(a51*a27);
  a27=(a27*a37);
  a27=(a48*a27);
  a39=(a39-a27);
  a27=(a51*a35);
  a27=(a48*a27);
  a39=(a39-a27);
  a35=(a15*a35);
  a35=(a52*a35);
  a39=(a39+a35);
  a51=(a51*a28);
  a52=(a52*a51);
  a39=(a39-a52);
  a09=(a09?a38:0);
  a39=(a39+a09);
  a15=(a15*a28);
  a48=(a48*a15);
  a39=(a39-a48);
  if (res[0]!=0) res[0][7]=a39;
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][11]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_zogpmc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_zogpmc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pacejka_model_zogpmc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_zogpmc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_zogpmc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_zogpmc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_zogpmc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
