/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pacejka_model_zogpmc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {31, 1, 1};

/* pacejka_model_zogpmc_expl_ode_fun:(i0[9],i1[3],i2[31])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][4] : 0;
  a01=sin(a01);
  a05=(a04*a01);
  a03=(a03-a05);
  if (res[0]!=0) res[0][0]=a03;
  a01=(a00*a01);
  a02=(a04*a02);
  a01=(a01+a02);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a01;
  a02=arg[2]? arg[2][22] : 0;
  a03=arg[2]? arg[2][23] : 0;
  a03=(a03*a00);
  a02=(a02-a03);
  a03=arg[0]? arg[0][6] : 0;
  a02=(a02*a03);
  a03=arg[2]? arg[2][27] : 0;
  a05=(a02*a03);
  a06=1.;
  a06=(a06-a03);
  a02=(a02*a06);
  a06=arg[0]? arg[0][7] : 0;
  a03=cos(a06);
  a07=(a02*a03);
  a05=(a05+a07);
  a07=arg[2]? arg[2][16] : 0;
  a08=arg[2]? arg[2][17] : 0;
  a09=arg[2]? arg[2][18] : 0;
  a10=arg[2]? arg[2][28] : 0;
  a11=(a00<a10);
  a12=3.;
  a13=2.;
  a13=(a13*a10);
  a12=(a12/a13);
  a14=arg[2]? arg[2][13] : 0;
  a15=(a14*a01);
  a15=(a04+a15);
  a16=(a15/a10);
  a16=(-a16);
  a16=atan(a16);
  a17=(a12*a16);
  a18=5.0000000000000000e-01;
  a19=(a18*a15);
  a20=casadi_sq(a10);
  a21=casadi_sq(a15);
  a22=(a20+a21);
  a19=(a19/a22);
  a17=(a17-a19);
  a17=(a17*a00);
  a19=-1.;
  a13=(a13*a10);
  a22=(a13*a10);
  a19=(a19/a22);
  a16=(a19*a16);
  a22=(a15/a13);
  a21=(a21+a20);
  a22=(a22/a21);
  a16=(a16+a22);
  a16=(a16*a00);
  a16=(a16*a00);
  a16=(a16*a00);
  a17=(a17+a16);
  a17=(a11?a17:0);
  a16=(!a11);
  a15=(-a15);
  a15=atan2(a15,a00);
  a15=(a06+a15);
  a15=(a16?a15:0);
  a17=(a17+a15);
  a09=(a09*a17);
  a09=atan(a09);
  a08=(a08*a09);
  a08=sin(a08);
  a07=(a07*a08);
  a06=sin(a06);
  a08=(a07*a06);
  a05=(a05-a08);
  a08=arg[2]? arg[2][14] : 0;
  a09=(a08*a04);
  a09=(a09*a01);
  a05=(a05+a09);
  a09=casadi_sign(a00);
  a17=arg[2]? arg[2][24] : 0;
  a15=arg[2]? arg[2][25] : 0;
  a15=(a15*a00);
  a17=(a17+a15);
  a15=arg[2]? arg[2][26] : 0;
  a15=(a15*a00);
  a15=(a15*a00);
  a17=(a17+a15);
  a09=(a09*a17);
  a05=(a05-a09);
  a05=(a05/a08);
  if (res[0]!=0) res[0][3]=a05;
  a05=arg[2]? arg[2][19] : 0;
  a09=arg[2]? arg[2][20] : 0;
  a17=arg[2]? arg[2][21] : 0;
  a15=arg[2]? arg[2][12] : 0;
  a22=(a15*a01);
  a22=(a22-a04);
  a18=(a18*a22);
  a04=casadi_sq(a22);
  a21=(a20+a04);
  a18=(a18/a21);
  a10=(a22/a10);
  a10=atan(a10);
  a12=(a12*a10);
  a18=(a18+a12);
  a18=(a18*a00);
  a19=(a19*a10);
  a13=(a22/a13);
  a04=(a04+a20);
  a13=(a13/a04);
  a19=(a19-a13);
  a19=(a19*a00);
  a19=(a19*a00);
  a19=(a19*a00);
  a18=(a18+a19);
  a11=(a11?a18:0);
  a22=atan2(a22,a00);
  a16=(a16?a22:0);
  a11=(a11+a16);
  a17=(a17*a11);
  a17=atan(a17);
  a09=(a09*a17);
  a09=sin(a09);
  a05=(a05*a09);
  a09=(a02*a06);
  a09=(a05+a09);
  a17=(a07*a03);
  a09=(a09+a17);
  a00=(a08*a00);
  a00=(a00*a01);
  a09=(a09-a00);
  a09=(a09/a08);
  if (res[0]!=0) res[0][4]=a09;
  a07=(a07*a14);
  a07=(a07*a03);
  a02=(a02*a14);
  a02=(a02*a06);
  a07=(a07+a02);
  a05=(a05*a15);
  a07=(a07-a05);
  a05=arg[2]? arg[2][15] : 0;
  a07=(a07/a05);
  if (res[0]!=0) res[0][5]=a07;
  a07=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a07;
  a07=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a07=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_zogpmc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_zogpmc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_zogpmc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pacejka_model_zogpmc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_zogpmc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_zogpmc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_zogpmc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_zogpmc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_zogpmc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
