/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {148, 1, 1};
static const casadi_int casadi_s3[3] = {12, 9, 1};

/* linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac:(i0[9],i1[3],i2[148])->(o0[9],o1[12x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110;
  a000=arg[2]? arg[2][0] : 0;
  a001=arg[0]? arg[0][0] : 0;
  a002=(a000*a001);
  a003=arg[2]? arg[2][9] : 0;
  a004=arg[0]? arg[0][1] : 0;
  a005=(a003*a004);
  a002=(a002+a005);
  a005=arg[2]? arg[2][18] : 0;
  a006=arg[0]? arg[0][2] : 0;
  a007=(a005*a006);
  a002=(a002+a007);
  a007=arg[2]? arg[2][27] : 0;
  a008=arg[0]? arg[0][3] : 0;
  a009=(a007*a008);
  a002=(a002+a009);
  a009=arg[2]? arg[2][36] : 0;
  a010=arg[0]? arg[0][4] : 0;
  a011=(a009*a010);
  a002=(a002+a011);
  a011=arg[2]? arg[2][45] : 0;
  a012=arg[0]? arg[0][5] : 0;
  a013=(a011*a012);
  a002=(a002+a013);
  a013=arg[2]? arg[2][54] : 0;
  a014=arg[0]? arg[0][6] : 0;
  a015=(a013*a014);
  a002=(a002+a015);
  a015=arg[2]? arg[2][63] : 0;
  a016=arg[0]? arg[0][7] : 0;
  a017=(a015*a016);
  a002=(a002+a017);
  a017=arg[2]? arg[2][72] : 0;
  a018=arg[0]? arg[0][8] : 0;
  a019=(a017*a018);
  a002=(a002+a019);
  a019=arg[2]? arg[2][81] : 0;
  a020=arg[1]? arg[1][0] : 0;
  a021=(a019*a020);
  a022=arg[2]? arg[2][90] : 0;
  a023=arg[1]? arg[1][1] : 0;
  a024=(a022*a023);
  a021=(a021+a024);
  a024=arg[2]? arg[2][99] : 0;
  a025=arg[1]? arg[1][2] : 0;
  a026=(a024*a025);
  a021=(a021+a026);
  a002=(a002+a021);
  a021=arg[2]? arg[2][108] : 0;
  a002=(a002+a021);
  if (res[0]!=0) res[0][0]=a002;
  a002=arg[2]? arg[2][1] : 0;
  a021=(a002*a001);
  a026=arg[2]? arg[2][10] : 0;
  a027=(a026*a004);
  a021=(a021+a027);
  a027=arg[2]? arg[2][19] : 0;
  a028=(a027*a006);
  a021=(a021+a028);
  a028=arg[2]? arg[2][28] : 0;
  a029=(a028*a008);
  a021=(a021+a029);
  a029=arg[2]? arg[2][37] : 0;
  a030=(a029*a010);
  a021=(a021+a030);
  a030=arg[2]? arg[2][46] : 0;
  a031=(a030*a012);
  a021=(a021+a031);
  a031=arg[2]? arg[2][55] : 0;
  a032=(a031*a014);
  a021=(a021+a032);
  a032=arg[2]? arg[2][64] : 0;
  a033=(a032*a016);
  a021=(a021+a033);
  a033=arg[2]? arg[2][73] : 0;
  a034=(a033*a018);
  a021=(a021+a034);
  a034=arg[2]? arg[2][82] : 0;
  a035=(a034*a020);
  a036=arg[2]? arg[2][91] : 0;
  a037=(a036*a023);
  a035=(a035+a037);
  a037=arg[2]? arg[2][100] : 0;
  a038=(a037*a025);
  a035=(a035+a038);
  a021=(a021+a035);
  a035=arg[2]? arg[2][109] : 0;
  a021=(a021+a035);
  if (res[0]!=0) res[0][1]=a021;
  a021=arg[2]? arg[2][2] : 0;
  a035=(a021*a001);
  a038=arg[2]? arg[2][11] : 0;
  a039=(a038*a004);
  a035=(a035+a039);
  a039=arg[2]? arg[2][20] : 0;
  a040=(a039*a006);
  a035=(a035+a040);
  a040=arg[2]? arg[2][29] : 0;
  a041=(a040*a008);
  a035=(a035+a041);
  a041=arg[2]? arg[2][38] : 0;
  a042=(a041*a010);
  a035=(a035+a042);
  a042=arg[2]? arg[2][47] : 0;
  a043=(a042*a012);
  a035=(a035+a043);
  a043=arg[2]? arg[2][56] : 0;
  a044=(a043*a014);
  a035=(a035+a044);
  a044=arg[2]? arg[2][65] : 0;
  a045=(a044*a016);
  a035=(a035+a045);
  a045=arg[2]? arg[2][74] : 0;
  a046=(a045*a018);
  a035=(a035+a046);
  a046=arg[2]? arg[2][83] : 0;
  a047=(a046*a020);
  a048=arg[2]? arg[2][92] : 0;
  a049=(a048*a023);
  a047=(a047+a049);
  a049=arg[2]? arg[2][101] : 0;
  a050=(a049*a025);
  a047=(a047+a050);
  a035=(a035+a047);
  a047=arg[2]? arg[2][110] : 0;
  a035=(a035+a047);
  if (res[0]!=0) res[0][2]=a035;
  a035=arg[2]? arg[2][3] : 0;
  a047=(a035*a001);
  a050=arg[2]? arg[2][12] : 0;
  a051=(a050*a004);
  a047=(a047+a051);
  a051=arg[2]? arg[2][21] : 0;
  a052=(a051*a006);
  a047=(a047+a052);
  a052=arg[2]? arg[2][30] : 0;
  a053=(a052*a008);
  a047=(a047+a053);
  a053=arg[2]? arg[2][39] : 0;
  a054=(a053*a010);
  a047=(a047+a054);
  a054=arg[2]? arg[2][48] : 0;
  a055=(a054*a012);
  a047=(a047+a055);
  a055=arg[2]? arg[2][57] : 0;
  a056=(a055*a014);
  a047=(a047+a056);
  a056=arg[2]? arg[2][66] : 0;
  a057=(a056*a016);
  a047=(a047+a057);
  a057=arg[2]? arg[2][75] : 0;
  a058=(a057*a018);
  a047=(a047+a058);
  a058=arg[2]? arg[2][84] : 0;
  a059=(a058*a020);
  a060=arg[2]? arg[2][93] : 0;
  a061=(a060*a023);
  a059=(a059+a061);
  a061=arg[2]? arg[2][102] : 0;
  a062=(a061*a025);
  a059=(a059+a062);
  a047=(a047+a059);
  a059=arg[2]? arg[2][111] : 0;
  a047=(a047+a059);
  if (res[0]!=0) res[0][3]=a047;
  a047=arg[2]? arg[2][4] : 0;
  a059=(a047*a001);
  a062=arg[2]? arg[2][13] : 0;
  a063=(a062*a004);
  a059=(a059+a063);
  a063=arg[2]? arg[2][22] : 0;
  a064=(a063*a006);
  a059=(a059+a064);
  a064=arg[2]? arg[2][31] : 0;
  a065=(a064*a008);
  a059=(a059+a065);
  a065=arg[2]? arg[2][40] : 0;
  a066=(a065*a010);
  a059=(a059+a066);
  a066=arg[2]? arg[2][49] : 0;
  a067=(a066*a012);
  a059=(a059+a067);
  a067=arg[2]? arg[2][58] : 0;
  a068=(a067*a014);
  a059=(a059+a068);
  a068=arg[2]? arg[2][67] : 0;
  a069=(a068*a016);
  a059=(a059+a069);
  a069=arg[2]? arg[2][76] : 0;
  a070=(a069*a018);
  a059=(a059+a070);
  a070=arg[2]? arg[2][85] : 0;
  a071=(a070*a020);
  a072=arg[2]? arg[2][94] : 0;
  a073=(a072*a023);
  a071=(a071+a073);
  a073=arg[2]? arg[2][103] : 0;
  a074=(a073*a025);
  a071=(a071+a074);
  a059=(a059+a071);
  a071=arg[2]? arg[2][112] : 0;
  a059=(a059+a071);
  if (res[0]!=0) res[0][4]=a059;
  a059=arg[2]? arg[2][5] : 0;
  a071=(a059*a001);
  a074=arg[2]? arg[2][14] : 0;
  a075=(a074*a004);
  a071=(a071+a075);
  a075=arg[2]? arg[2][23] : 0;
  a076=(a075*a006);
  a071=(a071+a076);
  a076=arg[2]? arg[2][32] : 0;
  a077=(a076*a008);
  a071=(a071+a077);
  a077=arg[2]? arg[2][41] : 0;
  a078=(a077*a010);
  a071=(a071+a078);
  a078=arg[2]? arg[2][50] : 0;
  a079=(a078*a012);
  a071=(a071+a079);
  a079=arg[2]? arg[2][59] : 0;
  a080=(a079*a014);
  a071=(a071+a080);
  a080=arg[2]? arg[2][68] : 0;
  a081=(a080*a016);
  a071=(a071+a081);
  a081=arg[2]? arg[2][77] : 0;
  a082=(a081*a018);
  a071=(a071+a082);
  a082=arg[2]? arg[2][86] : 0;
  a083=(a082*a020);
  a084=arg[2]? arg[2][95] : 0;
  a085=(a084*a023);
  a083=(a083+a085);
  a085=arg[2]? arg[2][104] : 0;
  a086=(a085*a025);
  a083=(a083+a086);
  a071=(a071+a083);
  a083=arg[2]? arg[2][113] : 0;
  a071=(a071+a083);
  if (res[0]!=0) res[0][5]=a071;
  a071=arg[2]? arg[2][6] : 0;
  a083=(a071*a001);
  a086=arg[2]? arg[2][15] : 0;
  a087=(a086*a004);
  a083=(a083+a087);
  a087=arg[2]? arg[2][24] : 0;
  a088=(a087*a006);
  a083=(a083+a088);
  a088=arg[2]? arg[2][33] : 0;
  a089=(a088*a008);
  a083=(a083+a089);
  a089=arg[2]? arg[2][42] : 0;
  a090=(a089*a010);
  a083=(a083+a090);
  a090=arg[2]? arg[2][51] : 0;
  a091=(a090*a012);
  a083=(a083+a091);
  a091=arg[2]? arg[2][60] : 0;
  a092=(a091*a014);
  a083=(a083+a092);
  a092=arg[2]? arg[2][69] : 0;
  a093=(a092*a016);
  a083=(a083+a093);
  a093=arg[2]? arg[2][78] : 0;
  a094=(a093*a018);
  a083=(a083+a094);
  a094=arg[2]? arg[2][87] : 0;
  a095=(a094*a020);
  a096=arg[2]? arg[2][96] : 0;
  a097=(a096*a023);
  a095=(a095+a097);
  a097=arg[2]? arg[2][105] : 0;
  a098=(a097*a025);
  a095=(a095+a098);
  a083=(a083+a095);
  a095=arg[2]? arg[2][114] : 0;
  a083=(a083+a095);
  if (res[0]!=0) res[0][6]=a083;
  a083=arg[2]? arg[2][7] : 0;
  a095=(a083*a001);
  a098=arg[2]? arg[2][16] : 0;
  a099=(a098*a004);
  a095=(a095+a099);
  a099=arg[2]? arg[2][25] : 0;
  a100=(a099*a006);
  a095=(a095+a100);
  a100=arg[2]? arg[2][34] : 0;
  a101=(a100*a008);
  a095=(a095+a101);
  a101=arg[2]? arg[2][43] : 0;
  a102=(a101*a010);
  a095=(a095+a102);
  a102=arg[2]? arg[2][52] : 0;
  a103=(a102*a012);
  a095=(a095+a103);
  a103=arg[2]? arg[2][61] : 0;
  a104=(a103*a014);
  a095=(a095+a104);
  a104=arg[2]? arg[2][70] : 0;
  a105=(a104*a016);
  a095=(a095+a105);
  a105=arg[2]? arg[2][79] : 0;
  a106=(a105*a018);
  a095=(a095+a106);
  a106=arg[2]? arg[2][88] : 0;
  a107=(a106*a020);
  a108=arg[2]? arg[2][97] : 0;
  a109=(a108*a023);
  a107=(a107+a109);
  a109=arg[2]? arg[2][106] : 0;
  a110=(a109*a025);
  a107=(a107+a110);
  a095=(a095+a107);
  a107=arg[2]? arg[2][115] : 0;
  a095=(a095+a107);
  if (res[0]!=0) res[0][7]=a095;
  a095=arg[2]? arg[2][8] : 0;
  a001=(a095*a001);
  a107=arg[2]? arg[2][17] : 0;
  a004=(a107*a004);
  a001=(a001+a004);
  a004=arg[2]? arg[2][26] : 0;
  a006=(a004*a006);
  a001=(a001+a006);
  a006=arg[2]? arg[2][35] : 0;
  a008=(a006*a008);
  a001=(a001+a008);
  a008=arg[2]? arg[2][44] : 0;
  a010=(a008*a010);
  a001=(a001+a010);
  a010=arg[2]? arg[2][53] : 0;
  a012=(a010*a012);
  a001=(a001+a012);
  a012=arg[2]? arg[2][62] : 0;
  a014=(a012*a014);
  a001=(a001+a014);
  a014=arg[2]? arg[2][71] : 0;
  a016=(a014*a016);
  a001=(a001+a016);
  a016=arg[2]? arg[2][80] : 0;
  a018=(a016*a018);
  a001=(a001+a018);
  a018=arg[2]? arg[2][89] : 0;
  a020=(a018*a020);
  a110=arg[2]? arg[2][98] : 0;
  a023=(a110*a023);
  a020=(a020+a023);
  a023=arg[2]? arg[2][107] : 0;
  a025=(a023*a025);
  a020=(a020+a025);
  a001=(a001+a020);
  a020=arg[2]? arg[2][116] : 0;
  a001=(a001+a020);
  if (res[0]!=0) res[0][8]=a001;
  if (res[1]!=0) res[1][0]=a019;
  if (res[1]!=0) res[1][1]=a022;
  if (res[1]!=0) res[1][2]=a024;
  if (res[1]!=0) res[1][3]=a000;
  if (res[1]!=0) res[1][4]=a003;
  if (res[1]!=0) res[1][5]=a005;
  if (res[1]!=0) res[1][6]=a007;
  if (res[1]!=0) res[1][7]=a009;
  if (res[1]!=0) res[1][8]=a011;
  if (res[1]!=0) res[1][9]=a013;
  if (res[1]!=0) res[1][10]=a015;
  if (res[1]!=0) res[1][11]=a017;
  if (res[1]!=0) res[1][12]=a034;
  if (res[1]!=0) res[1][13]=a036;
  if (res[1]!=0) res[1][14]=a037;
  if (res[1]!=0) res[1][15]=a002;
  if (res[1]!=0) res[1][16]=a026;
  if (res[1]!=0) res[1][17]=a027;
  if (res[1]!=0) res[1][18]=a028;
  if (res[1]!=0) res[1][19]=a029;
  if (res[1]!=0) res[1][20]=a030;
  if (res[1]!=0) res[1][21]=a031;
  if (res[1]!=0) res[1][22]=a032;
  if (res[1]!=0) res[1][23]=a033;
  if (res[1]!=0) res[1][24]=a046;
  if (res[1]!=0) res[1][25]=a048;
  if (res[1]!=0) res[1][26]=a049;
  if (res[1]!=0) res[1][27]=a021;
  if (res[1]!=0) res[1][28]=a038;
  if (res[1]!=0) res[1][29]=a039;
  if (res[1]!=0) res[1][30]=a040;
  if (res[1]!=0) res[1][31]=a041;
  if (res[1]!=0) res[1][32]=a042;
  if (res[1]!=0) res[1][33]=a043;
  if (res[1]!=0) res[1][34]=a044;
  if (res[1]!=0) res[1][35]=a045;
  if (res[1]!=0) res[1][36]=a058;
  if (res[1]!=0) res[1][37]=a060;
  if (res[1]!=0) res[1][38]=a061;
  if (res[1]!=0) res[1][39]=a035;
  if (res[1]!=0) res[1][40]=a050;
  if (res[1]!=0) res[1][41]=a051;
  if (res[1]!=0) res[1][42]=a052;
  if (res[1]!=0) res[1][43]=a053;
  if (res[1]!=0) res[1][44]=a054;
  if (res[1]!=0) res[1][45]=a055;
  if (res[1]!=0) res[1][46]=a056;
  if (res[1]!=0) res[1][47]=a057;
  if (res[1]!=0) res[1][48]=a070;
  if (res[1]!=0) res[1][49]=a072;
  if (res[1]!=0) res[1][50]=a073;
  if (res[1]!=0) res[1][51]=a047;
  if (res[1]!=0) res[1][52]=a062;
  if (res[1]!=0) res[1][53]=a063;
  if (res[1]!=0) res[1][54]=a064;
  if (res[1]!=0) res[1][55]=a065;
  if (res[1]!=0) res[1][56]=a066;
  if (res[1]!=0) res[1][57]=a067;
  if (res[1]!=0) res[1][58]=a068;
  if (res[1]!=0) res[1][59]=a069;
  if (res[1]!=0) res[1][60]=a082;
  if (res[1]!=0) res[1][61]=a084;
  if (res[1]!=0) res[1][62]=a085;
  if (res[1]!=0) res[1][63]=a059;
  if (res[1]!=0) res[1][64]=a074;
  if (res[1]!=0) res[1][65]=a075;
  if (res[1]!=0) res[1][66]=a076;
  if (res[1]!=0) res[1][67]=a077;
  if (res[1]!=0) res[1][68]=a078;
  if (res[1]!=0) res[1][69]=a079;
  if (res[1]!=0) res[1][70]=a080;
  if (res[1]!=0) res[1][71]=a081;
  if (res[1]!=0) res[1][72]=a094;
  if (res[1]!=0) res[1][73]=a096;
  if (res[1]!=0) res[1][74]=a097;
  if (res[1]!=0) res[1][75]=a071;
  if (res[1]!=0) res[1][76]=a086;
  if (res[1]!=0) res[1][77]=a087;
  if (res[1]!=0) res[1][78]=a088;
  if (res[1]!=0) res[1][79]=a089;
  if (res[1]!=0) res[1][80]=a090;
  if (res[1]!=0) res[1][81]=a091;
  if (res[1]!=0) res[1][82]=a092;
  if (res[1]!=0) res[1][83]=a093;
  if (res[1]!=0) res[1][84]=a106;
  if (res[1]!=0) res[1][85]=a108;
  if (res[1]!=0) res[1][86]=a109;
  if (res[1]!=0) res[1][87]=a083;
  if (res[1]!=0) res[1][88]=a098;
  if (res[1]!=0) res[1][89]=a099;
  if (res[1]!=0) res[1][90]=a100;
  if (res[1]!=0) res[1][91]=a101;
  if (res[1]!=0) res[1][92]=a102;
  if (res[1]!=0) res[1][93]=a103;
  if (res[1]!=0) res[1][94]=a104;
  if (res[1]!=0) res[1][95]=a105;
  if (res[1]!=0) res[1][96]=a018;
  if (res[1]!=0) res[1][97]=a110;
  if (res[1]!=0) res[1][98]=a023;
  if (res[1]!=0) res[1][99]=a095;
  if (res[1]!=0) res[1][100]=a107;
  if (res[1]!=0) res[1][101]=a004;
  if (res[1]!=0) res[1][102]=a006;
  if (res[1]!=0) res[1][103]=a008;
  if (res[1]!=0) res[1][104]=a010;
  if (res[1]!=0) res[1][105]=a012;
  if (res[1]!=0) res[1][106]=a014;
  if (res[1]!=0) res[1][107]=a016;
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
