/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {148, 1, 1};
static const casadi_int casadi_s5[3] = {6, 1, 1};
static const casadi_int casadi_s6[18] = 
  {12, 6, 0, 3, 6, 7, 8, 9,
  9, 3, 4, 11, 3, 4, 11, 0,
  1, 2};
static const casadi_int casadi_s7[3] = {6, 0, 1};

/* linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt:(i0[9],i1[3],i2[0],i3[],i4[148])->(o0[6],o1[12x6,9nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[4]? arg[4][122] : 0;
  a1=sin(a0);
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[4]? arg[4][117] : 0;
  a2=(a2-a3);
  a3=arg[4]? arg[4][119] : 0;
  a4=arg[0]? arg[0][8] : 0;
  a5=arg[4]? arg[4][121] : 0;
  a4=(a4-a5);
  a5=(a3*a4);
  a2=(a2-a5);
  a5=(a1*a2);
  a0=cos(a0);
  a6=arg[0]? arg[0][1] : 0;
  a7=arg[4]? arg[4][118] : 0;
  a6=(a6-a7);
  a7=arg[4]? arg[4][120] : 0;
  a4=(a7*a4);
  a6=(a6-a4);
  a4=(a0*a6);
  a5=(a5-a4);
  if (res[0]!=0) res[0][0]=a5;
  a2=(a0*a2);
  a6=(a1*a6);
  a2=(a2+a6);
  a2=(-a2);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a2=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][4]=a2;
  a2=1.;
  if (res[0]!=0) res[0][5]=a2;
  if (res[1]!=0) res[1][0]=a1;
  a6=(-a0);
  if (res[1]!=0) res[1][1]=a6;
  a5=(a0*a7);
  a4=(a1*a3);
  a5=(a5-a4);
  if (res[1]!=0) res[1][2]=a5;
  if (res[1]!=0) res[1][3]=a6;
  a6=(-a1);
  if (res[1]!=0) res[1][4]=a6;
  a0=(a0*a3);
  a1=(a1*a7);
  a0=(a0+a1);
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a2;
  if (res[1]!=0) res[1][8]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int linear_model_with_params_nx9_nu3_np31_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
